name: Slack chat.postMessage
on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: '#random'
          payload: |
            {
              "text": "aaaa",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "text": "GitHub Action build result: ${{ github.event.discussion.html_url }}\n${{ github.event.comment.html_url }}"
                  }
                }
              ]
            }
