name: Slack chat.postMessage
on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
jobs:
  discussion_commented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "#random"
          payload: |
            {
              "text": "通知メッセージ"
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Comment on discussion by <https://github.com/${{ github.event.sender.login }}| ${{ github.event.sender.login }}>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.comment.html_url }}"
                  }
                }
              ]
            }
