name: Hello, world!
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hogehoge'
      - run: echo 'aaaaa'
      - name: check out repo code
        uses: actions/checkout@v1
      - run: cat sample.txt
