name: Hello, world!
on: push

jobs:
  build:
    name: Check contens of the sample text
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cat sample.txt

name: Hoge
on: push

jobs:
  build:
    name: some test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hoge hoge'
