name: Hello, world!
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'echo something'
        run: echo 'hogehoge'
      - name: 'echo aaaaa'
        run: echo 'aaaaa'
      - name: check out repo code
        uses: actions/checkout@v1
      - run: cat sample.txt
